from . import sozla
from . import checker
from . import start
from . import translate
from . import sendBall
from . import admin
from . import main
from . import blokli
from . import sertifikat
from . import default
